image: ubuntu:latest

stages:
  - build

build:
  stage: build
  before_script:
    - >
      apt-get update && apt-get install -y --no-install-recommends
      build-essential
      curl
      ca-certificates
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2019-08-08
  script:
    - /root/.cargo/bin/cargo build --release
  after_script:
    - strip target/release/lodestone_news
  cache:
    paths:
      - target
  artifacts:
    paths:
      - target/release/lodestone_news
